--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/SimplifyLibasync
build-by-default: true
branches:
- main
projects:
  SimplifyLibasync:
    path: ""
    libs:
      - src: VennDev/VapmPMMP/VapmPMMP
        version: ^1.0
        epitope: .random
      - src: poggit/libasynql/libasynql
        version: ^4.2
        epitope: .random
...
